### PR TITLE
Add support for creating/ensuring mongodb indexes before server start

### PR DESCRIPTION
**Pull request by kprist**

### CODE REVIEW

**Comment by TBoonX** [comment]
Trying to create the indexes via the mongodb shell returns the following error:
```
{
	"ok" : 0,
	"errmsg" : "Values in v:2 index key pattern cannot be of type object. Only numbers > 0, numbers < 0, and strings are allowed.",
	"code" : 67,
	"codeName" : "CannotCreateIndex"
}
```

**Comment by kprist** [comment]
@TBoonX the method in mongo shell and in mongodb nodejs driver is different, compare http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#createIndexes to https://docs.mongodb.com/manual/reference/method/db.collection.createIndexes/

**Comment by TBoonX** [comment]
They differ only in the optional "options" parameter which is not there in the mongodb driver. The rest is identical and should work. (the driver docu refers to the origin docu)
Anyway I have to checkout this branch and run it. But my assumption is correct that this three indexes are correct ones and should work?

**Comment by kprist** [comment]
It's not identical, the driver links to this: https://docs.mongodb.com/manual/reference/command/createIndexes/#dbcmd.createIndexes it's different than what you probably used in mongo shell to get the error you posted.

Also, it's purely sample code, if you just run the service, it should automatically create them without problem.

**Review by TBoonX — APPROVED** [review]
Works. Good addition/preparation for easy index creation

**Pull request merged**
