### PR TITLE
Updated Libraries and implemented needed changes

### PR DESCRIPTION
**Pull request by rmeissn**
I've updated all libraries to the latest and greatest and have implemented needed changes (as some libs had been upgraded to a new major version). I also added a fix that @kprist mentioned about the linting.

Is there anything else that needs to be fixed in the template (as it will me merged to every other service and thus fix these issues there) or do we need some new libraries, functions, features, ....?

As some libs have been upgraded to a new major version, I had to alter the eslint config a lot. I haven't checked if all rules still apply, just fixed the ones that produced new errors. Additionally, ESLint v4 introduces some more strict rules (like for indention), that need to be handled on merged to the other services.

### CODE REVIEW

**Comment by rmeissn** [comment]
Please remove the "node_modules" folder and run `npm install` again to get all up to date libs.

**Review by TBoonX — APPROVED** [review]
Code look correct and works.

**Review by kprist — APPROVED** [review]
Why is this file, `application/tests/unit_slideDatabase.js` needed in this repo? Should we remove this ?

**Comment by rmeissn** [comment]
That is a template for unit-tests....like an example, matching the functionality of the template-service (because it's a very limited and small example for a deck-service). We had to implement something to show off the functionality in the beginning of the project.

**Comment by kprist** [comment]
@rmeissn another question, why do we have this line here: https://github.com/slidewiki/microservice-template/blob/master/application/server.js#L13

I have changed this in the deck service as I've found the default behaviour of joi validation (without this override) much more helpful. I've looked at the relevant commit but can't seem to figure out why this was put in: https://github.com/slidewiki/microservice-template/commit/10cc1f026e8c4927c85b9e090c6dca54cc1f6979

**Comment by rmeissn** [comment]
@kprist It has been implemented because Joi converted some strings (and other things) silently and that is not what was the intended behavior of a validation library (and caused some errors). The lib is supposed to tell me if something is wrong, instead of converting it to the format I want to have. It's also to encourage users of the API to use the right formats. E.g. if I want lowercase strings at the API, a user of the API is not supposed to issue uppercase strings.

**Comment by kprist** [comment]
Well I disagree, and I don't understand why you say this is not the *intended* behaviour of Joi, as it's the *default* behaviour, so I'm sure they deem it worthy! I consider it very useful for creating flexible APIs that are programmer-friendly. Joi handles both validation and normalization of input, which is quite useful in my opinion! I like that it validates the semantics of the request while relaxing a bit on the format. 

Any particular bugs you can remember that caused a lot of headache for someone here on slidewiki before you made this change ?

**Comment by rmeissn** [comment]
@athird had a bug for which we deactivated the default behavior. He might remember better than me.

**Comment by kprist** [comment]
Yes I had this discussion with @athird already, and I did review his code and actually the code related to that bug was eventually removed, but that's not relevant of course to the problem he had. He could easily just have overriden the default for this particular route that caused the bug. 

I'm looking at some code in user service actually that @TBoonX had commited it seems where he tries to do just that, convert strings to numbers (`util.parseStringToInteger`) or provide defaults for falsy values (`util.parseAPIParameter`), those are trivial using Joi validation with default for `convert`.

**Comment by TBoonX** [comment]
@kprist I do not get exactly what do you want to know but Joi at routes.js does not work with GET parameters. The validation gets skipped.  Thats why util.parseAPIParameter is still in the code and used. util.parseStringToInteger is also used for something I get from social providers (out of a json)

**Comment by athird** [comment]
I can't remember exactly when I had the issue, but I do remember it being quite a big headache to figure out that values were changing types "silently", and why. Surely it's more programmer-friendly to have things remaining as the types they're declared to be? :-)

**Comment by kprist** [comment]
@athird my experience with Joi was that I could declare something as being a number, and joi validation would convert any numerical strings to numbers, so I didn't have to use any `parseInt` code in my code, the input was of the correct type. It does the same for dates, you can support iso strings and your code will receive a `Date` object. It also supports stuff like "I want an array of objects but if you provide just one object, I can live with that and convert it to an array of one". It saves a lot of trouble when validating the entire payload and not worrying about invalid input further down the call stack.

@TBoonX I can see why that method is useful, it's just that I saw a bunch of lines where you used it for `request.payload` attributes, not `request.param`, and those lines could have been handled by proper joi schemata for sure.

**Comment by kprist** [comment]
@rmeissn another suggestion would be to replace the promise/always-catch rule (which seems to be obsolete):
`1:1  warning  Definition for rule 'promise/always-catch' was not found  promise/always-catch`

with the `promise/catch-or-return` rule:
https://github.com/xjamundx/eslint-plugin-promise

**Comment by athird** [comment]
@kprist I seem to remember, though I might be remembering wrongly, that I was expecting a string, but getting a number because the string input happened to be composed of all numbers.

**Comment by rmeissn** [comment]
@kprist There is no "promise/always-catch" rule anymore. I've exchanged that for the latest promise validation rules. If I missed one somewhere, please point me to the actual file.

About the JOI validation: service maintainers are free to change their services. Thus you can simply reactivate it at your service. I guess @athird won't do this it at his service. As it really introduced a very hard to track bug, I'm still for leaving the option as it currently is. But if it bothers you a lot, we can have a vote about it.

Any other requests, ideas or suggestions?

**Comment by kprist** [comment]
@rmeissn not that I can think of, and of course I agree that it's up to service maintainers to keep this or not.

**Pull request merged**
