### PR TITLE
SWIK-1818 Upgraded Travis NodeJS runtime to v8

### PR DESCRIPTION
**Pull request by rmeissn**
I've upgraded the NodeJS runtime to v8 (currently LTS) on Travis and for the platform-runtime.

Still testing, do not merge as of now.

### CODE REVIEW

**Comment by rmeissn** [comment]
Tested everything, seems fine to merge from my point of view.

**Review by TBoonX — COMMENTED** [review]
I builded and started a docker container and was not able to use mongodb. I am using mongo:3.4
71218/134713.439, [request,error] message: double colon in host identifier, stack: Error: double colon in host identifier
    at module.exports (/nodeApp/node_modules/mongodb/lib/url_parser.js:90:13)
    at connect (/nodeApp/node_modules/mongodb/lib/mongo_client.js:486:16)
    at /nodeApp/node_modules/mongodb/lib/mongo_client.js:240:7
    at new Promise (<anonymous>)
    at Function.MongoClient.connect (/nodeApp/node_modules/mongodb/lib/mongo_client.js:236:12)
    at Object.connectToDatabase (/nodeApp/database/helper.js:117:26)
    at Object.insert (/nodeApp/database/slideDatabase.js:21:19)
    at newSlide (/nodeApp/controllers/handler.js:28:13)
    at Object.internals.handler (/nodeApp/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/nodeApp/node_modules/hapi/lib/handler.js:32:23)

**Comment by rmeissn** [comment]
Works fine for me if I start the built container with `docker run -it --rm --link mongotest -e DATABASE_URL=mongotest -e DATABASE_PORT=27017 -p 3000:3000 IMAGE_NAME`

**Comment by TBoonX** [comment]
Now it worked on my machine too

**Review by kprist — APPROVED** [review]
I also tested this with the deck service by building a fresh image etc; server was up, connecting, tests passed, as far as we can tell it's ok

**Pull request merged**
