### PR TITLE
[proposal_docker_deploy] Updated Dockerfile

### PR DESCRIPTION
**Pull request by TBoonX**

### CODE REVIEW

**Comment by kprist** [comment]
I think it kind of fixes the problem, but:
1. @rmeissn suggested we create a separate `Dockerfile` (or something along those lines) for travis, and keep the default `Dockerfile` as it were, maybe with a simple `npm install --production` command
1. instead of the above, could we have a unified `Dockerfile` that uses environment variables to tell it's under travis so that it works differently?
1. `npm update` commands actually change the `package.json` file and upgrade the versions, so using them in a build environment means we would have different versions installed, and debugging issues might be problematic. Shouldn't we instead start adding the `package-lock.json` file recent versions of npm create into source control and therefore have identical builds?

**Comment by rmeissn** [comment]
According to https://stackoverflow.com/questions/31198835/can-we-pass-env-variables-through-cmd-line-while-building-a-docker-image-through , this seems possible via using the ARG directives. But I don't know whether this is possible on DockerHub.

**Comment by kprist** [comment]
@rmeissn looks nice, and even if we can't pass arguments to DockerHub, that is fine, because we'd need to create this `Dockerfile` with defaults in place, i.e. no arguments passed. That would actually be the best practice anyway, i.e. the build should succeed without setting the variables.

From the SO question you posted:
```
FROM php:7.0-fpm
ARG APP_ENV=local
ENV APP_ENV ${APP_ENV}
RUN cd /usr/local/etc/php && ln -sf php.ini-${APP_ENV} php.ini
```

The second line seems to provide a default, and the third line probably does nothing if `APP_ENV` is not set

**Comment by rmeissn** [comment]
About number 3.:
According to https://docs.npmjs.com/cli/update#recording-updates-with---save , npm update will not change the package.json file, but update all deps to the latest allowed dependency (like if you would clone a repo and execute npm install --> will fetch the latest version, that is allowed). How did you observed that it's modifying the package.json file?

**Comment by kprist** [comment]
@rmeissn I just ran the command `npm update --dev` (as it is in .travis.yml file) and noticed the package.json file was updated, had not seen the manual page you posted. Same thing happens with `npm update` as well.

However I realised that if i run `npm update` once and revert the changes to `package.json`, running `npm update` again does not change the `package.json`. This is generally weird behavior, but then I found this: https://github.com/npm/npm/releases/tag/v5.0.0 . It mentions that "npm will --save by default now." and links to twitter of all places: https://twitter.com/maybekatz/status/859229741676625920 .

So I'm guessing the question is, what npm version should we use? Plus, wouldn't it be better to add the package-lock.json file to source control so that we have better control over versions used across deployments, and dev environments ?

**Comment by rmeissn** [comment]
I've pushed the docker build env var option to this PR. Works perfectly for the Travis workflow and works as well if you omit the build-arg stuff (just executing `docker build ./`). @kprist does this resolve issue SWIK-1732 ?

We're currently sticking to node 6.x (LTS), that ships with npm 3.x. and want to update to 8, as soon as this becomes the LTS version. This stackoverflow answer states that package-locks are only available starting with npm 5.x. So we can't use it as of now. - https://stackoverflow.com/questions/44297803/package-lock-json-role

About the update to the package.json: Is it maybe just reordering the packages, e.g. because the checked in file does not list the packages in alphabetical order? - btw: If I execute `npm update`, the file is not changed.

**Comment by kprist** [comment]
I see, it's weird then that npm lets me upgrade itself to latest npm 5.x, as I too use node version 6 locally... anyway, as long as it works on our build systems it's fine, we can revisit once we upgrade node.

About the travis build fix, it looks OK, but I'll do an actual test tomorrow.

**Review by kprist — APPROVED** [review]
Tested this changeset on deck service, docker image builds fine using the simplest form, `docker build .`, and logs show node installation phase completes normally.

**Comment by bwulff** [comment]
didn't test, but seems to affect only travis build...

**Comment by kprist** [comment]
@bwulff not only the travis build, as it changes the Dockerfile; but when no env args are provided it's identical to what we have now (except for the node version part)

**Pull request merged**
